//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktikaodin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoeInventory
    {
        public string Обувь_ { get; set; }
        public int Размер_ { get; set; }
        public string Цвет_ { get; set; }
        public double Цена_ { get; set; }
    }
}
